"""Migration 0076: regenerating one scene is priced, confirmed, paid once, made
with the same source, and decided only by someone who may start runs.

What would break without these:

* another organization quotes, or regenerates (and pays with the victim's
  credits for) a scene of a tenant's video; a missing video and another
  organization's read differently (an oracle);
* a member who may only read the channel starts a paid regeneration;
* a replayed idempotency key holds twice or queues two jobs, or a reused key
  quietly runs a different request;
* the price changes between the quote and the press and the new price is
  held anyway; a press without a price spends;
* an unset price reads as 0 and runs for free;
* a failed regeneration keeps the credits, or replaces the old scene, or voids
  the approval of a cut that did not change;
* two presses at once hold twice or queue two jobs on one run;
* a scene made by a generator is regenerated by another one, or silently from
  stock; a published video is changed;
* a browser links a job to a regeneration, or a job is linked to another
  regeneration's hold, or a regeneration's job is held to the whole-video floor.

Isolation of scene_regenerations (read / update / delete / insert, row by row)
is covered by test_sec_isolation.py through sec_expectations.TABLES.
"""

from __future__ import annotations

import json
import threading
import uuid
from contextlib import contextmanager

import psycopg
from psycopg import sql

import sec_db
from sec_db import ANON, SERVICE, acting, as_superuser
from sec_scene_regen_0076 import held_id, manifest_json

# A generated scene (1 clip): 3 + 7 = 10. A stock scene: 3, floored to 5.
# video_minute is deliberately high: a regeneration is never held to the
# whole-video length floor.
PRICES = {"scene_regenerate": 3, "scene_regenerate_clip_kling": 7, "job_minimum": 5, "video_minute": 400}
GEN, STOCK = 10, 5


def owner(s):
    """The same transaction, read as the database owner: the ground truth an
    attack is checked against, before the rollback takes it away."""
    s.conn.execute("reset role")
    return s


def become(s, who):
    """The same transaction, continued as another API caller (the worker's
    service key after the person's press), so the whole story rolls back
    together."""
    s.conn.execute("reset role")
    s.conn.execute("select set_config('request.jwt.claims', %s, true)", [json.dumps(who.claims())])
    s.conn.execute("select set_config('request.jwt.claim.role', %s, true)", [who.role])
    s.conn.execute(sql.SQL("set local role {}").format(sql.Identifier(who.role)))
    return s


def _set_prices(su, prices):
    for unit, rate in prices.items():
        su.rows("insert into public.credit_prices (unit, credits_per_unit, margin) values (%s, %s, 0) "
                "on conflict (unit) do update set credits_per_unit = excluded.credits_per_unit, margin = 0 "
                "returning 1", [unit, rate])


def _held_video(su, t, slug, *, review_state="pending", **mkw):
    vid = held_id(t.channel, slug)
    su.rows("insert into public.videos (video_id, channel_id, title, slug, review_state, publish_state, manifest) "
            "values (%s, %s, 'Held', %s, %s, 'held', %s::jsonb) returning 1",
            [vid, t.channel, slug, review_state, manifest_json(**mkw)])
    return vid


@contextmanager
def world(conn, t, *, prices=PRICES, slug=None, **mkw):
    """A rolled-back world with the price list and one held (not uploaded)
    run of tenant ``t``. Everything made inside disappears with it."""
    with as_superuser(conn, commit=False) as su:
        if prices:
            _set_prices(su, prices)
        vid = _held_video(su, t, slug or f"regen-{t.key}", **mkw)
        yield su, vid


def quote(s, vid, scene="s000", source="same"):
    return s.run("select public.quote_scene_regenerate(%s, %s, %s)", [vid, scene, source])


def press(s, vid, scene="s000", *, prompt=None, source="same", max_credits=GEN, key=None):
    return s.run("select public.request_scene_regenerate(%s, %s, %s, %s, %s::numeric, %s)",
                 [vid, scene, prompt, source, max_credits, key or f"press-{uuid.uuid4().hex}"])


def holds(su, org, *, fresh=True) -> list:
    """The organization's regeneration holds — by default only those placed in
    this (rolled-back) transaction: now() is its start time."""
    return su.rows("select job_id, amount, status, captured from public.credit_reservations "
                   "where org_id = %s and job_id like 'rj-sr-%%' "
                   + ("and created_at >= now() " if fresh else "") + "order by created_at", [org])


def regens(su, vid) -> list:
    return su.rows("select id, status, source_kind, provider, model, explicit_stock, quoted_credits, credit_ref, "
                   "charged_credits, render_job_id from public.scene_regenerations where video_id = %s "
                   "order by created_at", [vid])


def jobs(su, vid) -> list:
    return su.rows("select j.id, j.kind, j.params, j.credit_ref, j.scene_regeneration_id from public.render_jobs j "
                   "join public.scene_regenerations r on r.id = j.scene_regeneration_id where r.video_id = %s",
                   [vid])


def available(su, org):
    return su.value("select balance - reserved from public.credit_accounts where org_id = %s", [org])


def _accept_invite(s):
    s.rows("select public.accept_org_invite(id) from public.my_invites() limit 1")


# ── who may ─────────────────────────────────────────────────────────────────

def test_another_org_can_neither_quote_nor_regenerate_and_nothing_is_held(conn, sc):
    with world(conn, sc.alice) as (su, vid):
        with acting(conn, sc.bob.actor) as s:
            q = quote(s, vid)
            p = press(s, vid)
            o = owner(s)
            assert holds(o, sc.alice.org) == [] and holds(o, sc.bob.org) == []
            assert regens(o, vid) == []
    assert not q.ok and q.sqlstate == "42501", q
    assert not p.ok and p.sqlstate == "42501", p


def test_a_missing_video_and_another_orgs_read_the_same(conn, sc):
    with world(conn, sc.alice) as (su, vid):
        with acting(conn, sc.bob.actor) as s:
            theirs, missing = press(s, vid), press(s, "run-00000000000000000000")
            tq, mq = quote(s, vid), quote(s, "run-00000000000000000000")
    assert (theirs.sqlstate, theirs.error) == (missing.sqlstate, missing.error), (theirs, missing)
    assert (tq.sqlstate, tq.error) == (mq.sqlstate, mq.error), (tq, mq)


def test_a_member_who_may_only_read_sees_the_price_but_cannot_press(conn, sc):
    # Ivan accepts his pending viewer invite into org A, in this transaction only.
    with world(conn, sc.alice) as (su, vid):
        with acting(conn, sc.invitee) as s:
            _accept_invite(s)
            q = quote(s, vid)
            p = press(s, vid)
            assert holds(owner(s), sc.alice.org) == []
    assert q.ok, q
    body = q.rows[0][0]
    assert body["status"] == "priced" and float(body["credits"]) == GEN and body["may_start"] is False, body
    assert not p.ok and p.sqlstate == "42501", p


def test_strangers_and_anon_cannot_quote_or_press(conn, sc):
    with world(conn, sc.bob) as (su, vid):
        with acting(conn, sc.stranger) as s:
            sq, sp = quote(s, vid), press(s, vid)
        with acting(conn, ANON) as s:
            aq, ap = quote(s, vid), press(s, vid)
    for o in (sq, sp, aq, ap):
        assert not o.ok and o.sqlstate == "42501", o


def test_the_worker_functions_are_not_the_browsers(conn, sc):
    with world(conn, sc.bob) as (su, vid):
        with acting(conn, sc.bob.actor) as s:
            first = press(s, vid)
            rid = first.rows[0][0]["id"]
            job = first.rows[0][0]["render_job_id"]
            start = s.run("select public.start_scene_regeneration(%s, %s)", [rid, job])
            finish = s.run("select public.finish_scene_regeneration(%s, %s, true, null, null, null)", [rid, job])
            expire = s.run("select public.expire_scene_regenerations()")
            write = s.run("update public.scene_regenerations set status = 'succeeded' where id = %s", [rid])
    for o in (start, finish, expire):
        assert not o.ok and o.sqlstate == "42501", o
    assert not write.ok or write.rowcount == 0, write


# ── the money ───────────────────────────────────────────────────────────────

def test_the_press_holds_exactly_the_quote_and_queues_one_repair_of_that_scene(conn, sc):
    with world(conn, sc.bob) as (su, vid):
        before = available(su, sc.bob.org)
        with acting(conn, sc.bob.actor) as s:
            q = quote(s, vid)
            p = press(s, vid, prompt="the harbour at dawn, wider")
            o = owner(s)
            h, r, j = holds(o, sc.bob.org), regens(o, vid), jobs(o, vid)
            after = available(o, sc.bob.org)
    assert q.ok and float(q.rows[0][0]["credits"]) == GEN, q
    # BR-L-031: what a member reads over PostgREST is display-safe — no
    # generator, model or price-unit name, only the kind of source.
    body = q.rows[0][0]
    assert body["source_kind"] == "generated", body
    assert not {"provider", "model", "missing_unit", "unit", "clip_unit"} & set(body), body
    assert "kling" not in json.dumps(body), body
    assert p.ok, p
    assert len(h) == 1 and float(h[0][1]) == GEN and h[0][2] == "open", h
    assert float(before) - float(after) == GEN
    assert len(r) == 1
    _, status, kind, provider, model, explicit, quoted, ref, charged, job_id = r[0]
    # The same generator the scene was made with, never another one.
    assert (status, kind, provider, model, explicit) == ("queued", "generated", "kling", "kling-v2-6", False)
    assert float(quoted) == GEN and ref == h[0][0] and charged is None
    assert len(j) == 1 and j[0][0] == job_id and j[0][1] == "repair" and j[0][3] == ref
    assert j[0][2] == {"topic": f"regen-{sc.bob.key}", "repair_scenes": "s000"}, j[0][2]


def test_a_replayed_key_returns_the_same_job_and_holds_once(conn, sc):
    with world(conn, sc.bob) as (su, vid):
        with acting(conn, sc.bob.actor) as s:
            a = press(s, vid, key="same-key-123")
            b = press(s, vid, key="same-key-123")
            # The same key for a different request is refused, not run.
            c = press(s, vid, key="same-key-123", prompt="something else")
            o = owner(s)
            h, r = holds(o, sc.bob.org), regens(o, vid)
    assert a.ok and b.ok, (a, b)
    assert a.rows[0][0]["id"] == b.rows[0][0]["id"] and b.rows[0][0]["replayed"] is True
    assert a.rows[0][0]["render_job_id"] == b.rows[0][0]["render_job_id"]
    assert not c.ok and c.sqlstate == "NS409" and "idempotency_conflict" in c.error, c
    assert len(h) == 1 and len(r) == 1


def test_a_changed_price_is_refused_and_nothing_is_held(conn, sc):
    with world(conn, sc.bob) as (su, vid):
        with acting(conn, sc.bob.actor) as s:
            seen = float(quote(s, vid).rows[0][0]["credits"])
        # The owner raises the price after the person saw it.
        _set_prices(su, {"scene_regenerate_clip_kling": 9})
        with acting(conn, sc.bob.actor) as s:
            changed = press(s, vid, max_credits=seen)
            unpriced_press = press(s, vid, max_credits=None)
            o = owner(s)
            assert holds(o, sc.bob.org) == [] and regens(o, vid) == []
    assert seen == GEN
    assert not changed.ok and changed.sqlstate == "NS409" and "price_changed" in changed.error, changed
    assert not unpriced_press.ok and unpriced_press.sqlstate == "22023" and "price_required" in unpriced_press.error


def test_an_unset_price_is_unpriced_never_zero_and_cannot_be_pressed(conn, sc):
    with as_superuser(conn, commit=False) as su:
        su.rows("delete from public.credit_prices where unit like 'scene_regenerate%%' returning 1")
        _set_prices(su, {"scene_regenerate": 3})  # the per-clip unit stays unset
        vid = _held_video(su, sc.bob, "regen-unpriced")
        with acting(conn, sc.bob.actor) as s:
            q = quote(s, vid)
            p = press(s, vid, max_credits=1000)
            stock = quote(s, vid, scene="s001")
            assert holds(owner(s), sc.bob.org) == []
    body = q.rows[0][0]
    assert body["status"] == "unpriced" and body["credits"] is None, body
    # BR-L-031: the missing unit is the owner's to read in the price list,
    # not named to a member (it would name the generator).
    assert "missing_unit" not in body and "kling" not in json.dumps(body), body
    assert not p.ok and p.sqlstate == "NS400" and "unpriced" in p.error, p
    assert "kling" not in str(p.error) and "kling" not in str(getattr(p, "detail", "") or ""), p
    # The stock scene needs only the base unit: priced, at least job_minimum.
    assert stock.rows[0][0]["status"] == "priced", stock


def test_a_failed_regeneration_releases_the_hold_and_keeps_the_old_scene(conn, sc):
    with world(conn, sc.bob, review_state="approved") as (su, vid):
        before = available(su, sc.bob.org)
        old_manifest = su.value("select manifest from public.videos where video_id = %s", [vid])
        with acting(conn, sc.bob.actor) as s:
            body = press(s, vid).rows[0][0]
            become(s, SERVICE)
            started = s.value("select public.start_scene_regeneration(%s, %s)", [body["id"], body["render_job_id"]])
            ended = s.value("select public.finish_scene_regeneration(%s, %s, false, 'provider_unavailable', "
                            "'the generator is not configured on this worker', null)",
                            [body["id"], body["render_job_id"]])
            again = s.value("select public.finish_scene_regeneration(%s, %s, true, null, null, null)",
                            [body["id"], body["render_job_id"]])
            o = owner(s)
            h, r = holds(o, sc.bob.org), regens(o, vid)
            after = available(o, sc.bob.org)
            v = o.rows("select manifest, review_state from public.videos where video_id = %s", [vid])[0]
    assert started["provider"] == "kling" and started["model"] == "kling-v2-6", started
    assert ended["status"] == "failed" and again["replayed"] is True and again["status"] == "failed"
    assert h[0][2] == "released" and h[0][3] is None, h
    assert float(after) == float(before), "a failed regeneration kept credits"
    assert r[0][1] == "failed" and float(r[0][8]) == 0
    # The old scene stays: the Video IR is untouched and so is the approval
    # of a cut that did not change.
    assert v[0] == old_manifest and v[1] == "approved", v


def test_a_finished_regeneration_captures_the_quote_and_voids_the_approval(conn, sc):
    with world(conn, sc.bob, review_state="approved") as (su, vid):
        before = available(su, sc.bob.org)
        su.rows("insert into public.review_intents (channel_id, video_id, action) values (%s, %s, 'approve') "
                "returning 1", [sc.bob.channel, vid])
        with acting(conn, sc.bob.actor) as s:
            body = press(s, vid).rows[0][0]
            become(s, SERVICE)
            s.value("select public.start_scene_regeneration(%s, %s)", [body["id"], body["render_job_id"]])
            done = s.value("select public.finish_scene_regeneration(%s, %s, true, null, null, %s::jsonb)",
                           [body["id"], body["render_job_id"], json.dumps({"new_asset_ids": ["a_new0"]})])
            o = owner(s)
            h = holds(o, sc.bob.org)
            after = available(o, sc.bob.org)
            state = o.value("select review_state from public.videos where video_id = %s", [vid])
            waiting = o.value("select count(*) from public.review_intents where video_id = %s "
                              "and action = 'approve' and consumed_at is null", [vid])
    assert done["status"] == "succeeded" and float(done["charged_credits"]) == GEN
    assert h[0][2] == "captured" and float(h[0][3]) <= float(h[0][1]) == GEN, h
    assert float(before) - float(after) == GEN
    # Re-approval goes through the normal review; nothing here published.
    assert state == "pending" and waiting == 0


def test_a_lost_job_is_failed_and_released_by_the_sweep(conn, sc):
    with world(conn, sc.bob) as (su, vid):
        before = available(su, sc.bob.org)
        with acting(conn, sc.bob.actor) as s:
            body = press(s, vid).rows[0][0]
            owner(s).rows("update public.render_jobs set status = 'failed', finished_at = now() - interval '1 hour' where id = %s "
                          "returning 1", [body["render_job_id"]])
            become(s, SERVICE)
            n = s.value("select public.expire_scene_regenerations()")
            start = s.value("select public.start_scene_regeneration(%s, %s)", [body["id"], body["render_job_id"]])
            o = owner(s)
            r, after = regens(o, vid), available(o, sc.bob.org)
    assert n >= 1 and start is None
    assert r[0][1] == "failed" and float(after) == float(before)


def test_two_presses_at_once_hold_once_and_queue_one_job(conn, sc):
    """Two sessions press for the same video concurrently with different keys:
    one wins, the other waits and is refused as in progress before anything is
    held. Real sessions must commit, so this test puts the world back itself."""
    with as_superuser(conn) as su:
        had = {r[0]: (r[1], r[2]) for r in su.rows(
            "select unit, credits_per_unit, margin from public.credit_prices where unit = any(%s)", [list(PRICES)])}
        _set_prices(su, PRICES)
        vid = _held_video(su, sc.bob, "regen-race")
    dsn = psycopg.conninfo.make_conninfo(sec_db.admin_dsn(), dbname=conn.info.dbname)
    barrier = threading.Barrier(2)
    results = []

    def go():
        with psycopg.connect(dsn, autocommit=True) as c:
            with acting(c, sc.bob.actor, commit=True) as s:
                barrier.wait()
                results.append(press(s, vid))

    threads = [threading.Thread(target=go) for _ in range(2)]
    try:
        for t in threads:
            t.start()
        for t in threads:
            t.join(30)
        assert sorted(r.ok for r in results) == [False, True], results
        loser = next(r for r in results if not r.ok)
        assert loser.sqlstate == "NS409" and "in_progress" in loser.error, loser
        with as_superuser(conn, commit=False) as su:
            assert len(regens(su, vid)) == 1 and len(jobs(su, vid)) == 1
            assert len([h for h in holds(su, sc.bob.org, fresh=False) if h[2] == "open"]) == 1
    finally:
        with as_superuser(conn) as su:
            su.rows("update public.render_jobs set status = 'cancelled', finished_at = now() - interval '1 hour' "
                    "where scene_regeneration_id in (select id from public.scene_regenerations where video_id = %s) "
                    "returning 1", [vid])
        with acting(conn, SERVICE, commit=True) as s:
            s.value("select public.expire_scene_regenerations()")
        with as_superuser(conn) as su:
            su.rows("delete from public.videos where video_id = %s returning 1", [vid])
            for unit in PRICES:
                if unit in had:
                    su.rows("update public.credit_prices set credits_per_unit = %s, margin = %s where unit = %s "
                            "returning 1", [had[unit][0], had[unit][1], unit])
                else:
                    su.rows("delete from public.credit_prices where unit = %s returning 1", [unit])
            assert not [h for h in holds(su, sc.bob.org, fresh=False) if h[2] == "open"], "the race left a hold open"


def test_a_second_press_while_one_is_queued_is_in_progress_and_holds_nothing(conn, sc):
    with world(conn, sc.bob) as (su, vid):
        with acting(conn, sc.bob.actor) as s:
            first = press(s, vid)
            second = press(s, vid, scene="s001", max_credits=STOCK)
            q = quote(s, vid, scene="s001")
            h = holds(owner(s), sc.bob.org)
    assert first.ok and not second.ok and second.sqlstate == "NS409" and "in_progress" in second.error
    assert q.rows[0][0]["status"] == "unavailable" and q.rows[0][0]["reason"] == "in_progress"
    assert len(h) == 1


# ── the source ──────────────────────────────────────────────────────────────

def test_a_scene_whose_generator_was_not_recorded_is_unavailable_never_stock(conn, sc):
    with world(conn, sc.bob) as (su, vid):
        with acting(conn, sc.bob.actor) as s:
            q = quote(s, vid, scene="s002")
            p = press(s, vid, scene="s002", max_credits=1000)
            assert holds(owner(s), sc.bob.org) == []
    body = q.rows[0][0]
    assert body["status"] == "unavailable" and body["reason"] == "generator_not_recorded", body
    assert body["had_generated"] is True
    assert not p.ok and p.sqlstate == "NS400" and "scene_unavailable" in p.error, p


def test_stock_for_a_generated_scene_only_when_chosen_and_it_is_recorded(conn, sc):
    with world(conn, sc.bob) as (su, vid):
        with acting(conn, sc.bob.actor) as s:
            q = quote(s, vid, scene="s002", source="stock")
            p = press(s, vid, scene="s002", source="stock", max_credits=STOCK)
            o = owner(s)
            r = regens(o, vid)
    assert q.rows[0][0]["status"] == "priced" and float(q.rows[0][0]["credits"]) == STOCK
    assert p.ok, p
    _, status, kind, provider, model, explicit, quoted, *_ = r[0]
    assert (kind, provider, model, explicit, float(quoted)) == ("stock", None, None, True, STOCK)


def test_a_stock_scene_is_made_again_from_stock_and_is_not_marked_as_a_choice(conn, sc):
    with world(conn, sc.bob) as (su, vid):
        with acting(conn, sc.bob.actor) as s:
            p = press(s, vid, scene="s001", max_credits=STOCK)
            r = regens(owner(s), vid)
    assert p.ok, p
    assert (r[0][2], r[0][5]) == ("stock", False)


def test_a_published_video_cannot_be_regenerated_and_the_quote_says_why(conn, sc):
    with as_superuser(conn, commit=False) as su:
        _set_prices(su, PRICES)
        su.rows("update public.videos set manifest = %s::jsonb where video_id = %s returning 1",
                [manifest_json(), sc.bob.video])
        with acting(conn, sc.bob.actor) as s:
            q = quote(s, sc.bob.video)
            p = press(s, sc.bob.video)
            assert holds(owner(s), sc.bob.org) == []
    assert q.rows[0][0]["status"] == "unavailable" and q.rows[0][0]["reason"] == "published"
    assert not p.ok and p.sqlstate == "NS409" and "published" in p.error, p


def test_bad_input_is_refused_before_anything_is_held(conn, sc):
    with world(conn, sc.bob) as (su, vid):
        with acting(conn, sc.bob.actor) as s:
            bad = [press(s, vid, scene="3"), press(s, vid, source="best"),
                   press(s, vid, prompt="x" * 1001), press(s, vid, prompt="a\x07b"),
                   press(s, vid, key="short"), press(s, vid, key="bad key with spaces")]
            assert holds(owner(s), sc.bob.org) == []
    for o in bad:
        assert not o.ok and o.sqlstate == "22023", o


# ── the render queue ────────────────────────────────────────────────────────

def test_a_browser_cannot_link_a_job_to_a_regeneration(conn, sc):
    with world(conn, sc.bob) as (su, vid):
        with acting(conn, sc.bob.actor) as s:
            rid = press(s, vid).rows[0][0]["id"]
            ref = s.value("select public.reserve_credits(%s, %s, 60)",
                          [sc.bob.org, "rj-" + uuid.uuid4().hex])["job_id"]
            daily = s.run("insert into public.render_jobs (channel_id, kind, params, requested_by, credit_ref, "
                          "scene_regeneration_id) values (%s, 'daily', '{}'::jsonb, auth.uid(), %s, %s)",
                          [sc.bob.channel, ref, rid])
            repair = s.run("insert into public.render_jobs (channel_id, kind, params, requested_by, credit_ref, "
                           "scene_regeneration_id) values (%s, 'repair', %s::jsonb, auth.uid(), %s, %s)",
                           [sc.bob.channel, json.dumps({"topic": f"regen-{sc.bob.key}", "repair_scenes": "s000"}),
                            ref, rid])
            relink = s.run("update public.render_jobs set scene_regeneration_id = null "
                           "where scene_regeneration_id = %s", [rid])
    assert not daily.ok and daily.sqlstate == "42501", daily
    assert not repair.ok and repair.sqlstate == "42501", repair
    assert not relink.ok or relink.rowcount == 0, relink


def test_the_insert_policy_itself_refuses_a_browser_link_to_a_regeneration(conn, sc):
    """BR-L-030: the payment guard (a BEFORE trigger) refuses the link first,
    so the test above cannot tell whether render_jobs_insert's own clause
    (`scene_regeneration_id is null`) is there. Here the guard is switched off
    inside the rolled-back world: the policy alone must still refuse the link,
    and the same insert without the link must pass it (the clause is the reason)."""
    with world(conn, sc.bob) as (su, vid):
        with acting(conn, sc.bob.actor) as s:
            rid = press(s, vid).rows[0][0]["id"]
        su.run("alter table public.render_jobs disable trigger render_jobs_payment_guard")
        with acting(conn, sc.bob.actor) as s:
            linked = s.run("insert into public.render_jobs (channel_id, kind, params, requested_by, "
                           "scene_regeneration_id) values (%s, 'daily', '{}'::jsonb, auth.uid(), %s)",
                           [sc.bob.channel, rid])
        with acting(conn, sc.bob.actor) as s:
            plain = s.run("insert into public.render_jobs (channel_id, kind, params, requested_by) "
                          "values (%s, 'daily', '{}'::jsonb, auth.uid())", [sc.bob.channel])
        su.run("alter table public.render_jobs enable trigger render_jobs_payment_guard")
    assert not linked.ok and linked.sqlstate == "42501", linked
    assert "row-level security" in str(linked.error), linked
    assert plain.ok, plain


def test_the_service_key_cannot_pay_a_regeneration_job_with_another_hold(conn, sc):
    with world(conn, sc.bob) as (su, vid):
        with acting(conn, sc.bob.actor) as s:
            body = press(s, vid).rows[0][0]
            o = owner(s)
            # Room for a second open hold, whatever the plan's parallel limit.
            o.rows("update public.credit_reservations set status = 'released', settled_at = now() "
                   "where job_id = %s returning 1", [body["credit_ref"]])
            # Unlink its job, past the frozen-terms trigger, so the guard is
            # what is tested.
            o.conn.execute("set local session_replication_role = replica")
            o.rows("delete from public.render_jobs where scene_regeneration_id = %s returning 1", [body["id"]])
            o.rows("update public.scene_regenerations set render_job_id = null where id = %s returning 1",
                   [body["id"]])
            o.conn.execute("set local session_replication_role = origin")
            ref = o.value("select public.reserve_credits(%s, %s, 500)", [sc.bob.org, "rj-" + uuid.uuid4().hex])
            become(s, SERVICE)
            # A regeneration paid by an ordinary queue hold, not its own.
            out = s.run("insert into public.render_jobs (channel_id, kind, params, credit_ref, scene_regeneration_id) "
                        "values (%s, 'repair', %s::jsonb, %s, %s)",
                        [sc.bob.channel, json.dumps({"topic": f"regen-{sc.bob.key}", "repair_scenes": "s000"}),
                         ref["job_id"], body["id"]])
            # Another scene than the one priced, with its own hold.
            other = s.run("insert into public.render_jobs (channel_id, kind, params, credit_ref, scene_regeneration_id) "
                          "values (%s, 'repair', %s::jsonb, %s, %s)",
                          [sc.bob.channel, json.dumps({"topic": f"regen-{sc.bob.key}", "repair_scenes": "s001"}),
                           body["credit_ref"], body["id"]])
    assert not out.ok and out.sqlstate == "42501", out
    assert not other.ok and other.sqlstate == "42501", other


def test_an_ended_regeneration_is_final(conn, sc):
    with world(conn, sc.bob) as (su, vid):
        with acting(conn, sc.bob.actor) as s:
            body = press(s, vid).rows[0][0]
            become(s, SERVICE)
            s.value("select public.finish_scene_regeneration(%s, %s, false, 'failed', 'x', null)",
                    [body["id"], body["render_job_id"]])
            o = owner(s)
            out = o.run("update public.scene_regenerations set status = 'queued', finished_at = null "
                        "where id = %s", [body["id"]])
            gone = o.run("delete from public.scene_regenerations where id = %s", [body["id"]])
    assert not out.ok and out.sqlstate == "42501", out
    assert not gone.ok and gone.sqlstate == "42501", gone
