// Static image imports (`import shot from "./x.webp"`) are typed by Next's own
// declarations. next-env.d.ts carries them too, but it is generated by a build
// and not committed, so `tsc` on a fresh checkout (CI runs it before the build)
// would not know them.
/// <reference types="next/image-types/global" />
